---
paths: 
    base_path: ../..  # abs or relative to HOME
    code_core:  # paths to external python code base
        - Sites/Bio/panelseq/code/py  # abs or relative to HOME
    output_path: testoutput # relative to base_path
    OverviewSeq_excel: ../../testdata/testSamplesSequencing.xlsx # abs or relative to HOME
Run:
    InvestigatorName: Martin Szyska
    ProjectName: LungPanelSequencing
    ExperimentName: 221116-LungPanel_1
    Date: 16/11/22
    Workflow: GenerateFASTQ     # GenerateFASTQ for direct demultiplexing
    Library Prep Kit: Custom
    Chemistry: Default
    Reads: [151, 151] # here set the required cycles for running PE sequencing +1 as a list