---
paths: 
    base_path: <repopath>  # abs or relative to HOME
    code_core:  # paths to external python code base
        - <repopath>/code/py  # abs or relative to HOME
    output_path: testoutput # relative to base_path
    OverviewSeq_excel: <repopath>/testdata/testSamplesSequencing.xlsx # abs or relative to HOME
Run:
    InvestigatorName: Jane Doe
    ProjectName: Generic Sequencing
    ExperimentName: 222222-Seq_1
    Date: 22/22/22
    Workflow: GenerateFASTQ     # GenerateFASTQ for direct demultiplexing
    Library Prep Kit: Custom
    Chemistry: Default
    Reads: [151, 151] # here set the required cycles for running PE sequencing +1 as a list