---
code: 
    py_core:
        - Sites/Bio/panelseq/code/py  # abs or relative to HOME
paths: 
    base_path: Sites/Bio/panelseq  # abs or relative to HOME
    output_path: testoutput # relative to base_path
    OverviewSeq_excel: Sites/Bio/panelseq/testdata/testSamplesSequencing.xlsx # abs or relative to HOME
Run:
    InvestigatorName: Jane Doe
    ProjectName: Generic Sequencing
    ExperimentName: 222222-Seq_1
    Date: 22/22/22
    Workflow: GenerateFASTQ     # GenerateFASTQ for direct demultiplexing
    Library Prep Kit: Custom
    Chemistry: Default
    Reads: [151, 151] # here set the required cycles for running PE sequencing +1 as a list